In [1]:
import tensorflow as tf

In [2]:
layer = tf.keras.layers.Dense(4, activation=tf.nn.sigmoid)

In [29]:
x = tf.random.normal([2,3])
print (x)

tf.Tensor(
[[-0.15682119 -0.2171534  -1.5727938  -0.20752263]
 [ 0.6697627   0.18425506 -0.11356848 -0.8887865 ]], shape=(2, 4), dtype=float32)


In [25]:
y = layer(x)
layer.kernel.shape, y.shape

(TensorShape([4, 4]), TensorShape([2, 4]))

In [26]:
with tf.GradientTape(persistent=True) as tape:
    #y = layer(x)
    y = tf.matmul(x,layer.kernel)
    z = tf.sigmoid(y)
    tape.watch(z)
j = tape.jacobian(z, y)
j

<tf.Tensor: shape=(2, 4, 2, 4), dtype=float32, numpy=
array([[[[0.23882198, 0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        , 0.        ]],

        [[0.        , 0.20219938, 0.        , 0.        ],
         [0.        , 0.        , 0.        , 0.        ]],

        [[0.        , 0.        , 0.2476294 , 0.        ],
         [0.        , 0.        , 0.        , 0.        ]],

        [[0.        , 0.        , 0.        , 0.24545556],
         [0.        , 0.        , 0.        , 0.        ]]],


       [[[0.        , 0.        , 0.        , 0.        ],
         [0.16883923, 0.        , 0.        , 0.        ]],

        [[0.        , 0.        , 0.        , 0.        ],
         [0.        , 0.14157806, 0.        , 0.        ]],

        [[0.        , 0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.20261309, 0.        ]],

        [[0.        , 0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ,

In [3]:
import tensorflow as tf
#create a Sigmoid layer with 4 output neurons
tf.random.set_seed(42)
layer = tf.keras.layers.Dense(4, activation=tf.nn.sigmoid)
#create a input tensor 3 neurons
x = tf.random.normal([2,3])
z = layer(x)
z.shape

TensorShape([2, 4])

In [56]:
with tf.GradientTape(persistent=True) as tape:
    #y = layer(x)
    y = tf.matmul(x,layer.kernel)
    z = tf.sigmoid(y)
    tape.watch(z)
j1 = tape.jacobian(y, layer.kernel)
j1

<tf.Tensor: shape=(2, 4, 3, 4), dtype=float32, numpy=
array([[[[ 0.3274685,  0.       ,  0.       ,  0.       ],
         [-0.8426258,  0.       ,  0.       ,  0.       ],
         [ 0.3194337,  0.       ,  0.       ,  0.       ]],

        [[ 0.       ,  0.3274685,  0.       ,  0.       ],
         [ 0.       , -0.8426258,  0.       ,  0.       ],
         [ 0.       ,  0.3194337,  0.       ,  0.       ]],

        [[ 0.       ,  0.       ,  0.3274685,  0.       ],
         [ 0.       ,  0.       , -0.8426258,  0.       ],
         [ 0.       ,  0.       ,  0.3194337,  0.       ]],

        [[ 0.       ,  0.       ,  0.       ,  0.3274685],
         [ 0.       ,  0.       ,  0.       , -0.8426258],
         [ 0.       ,  0.       ,  0.       ,  0.3194337]]],


       [[[-1.4075519,  0.       ,  0.       ,  0.       ],
         [-2.3880599,  0.       ,  0.       ,  0.       ],
         [-1.0392479,  0.       ,  0.       ,  0.       ]],

        [[ 0.       , -1.4075519,  0.       ,  0.

In [4]:
with tf.GradientTape(persistent=True) as tape:
    z = layer(x)
j = tape.jacobian(z, layer.kernel)
print(j)

tf.Tensor(
[[[[ 0.07960078  0.          0.          0.        ]
   [-0.20482479  0.          0.          0.        ]
   [ 0.07764768  0.          0.          0.        ]]

  [[ 0.          0.07504999  0.          0.        ]
   [ 0.         -0.19311492  0.          0.        ]
   [ 0.          0.07320855  0.          0.        ]]

  [[ 0.          0.          0.0754204   0.        ]
   [ 0.          0.         -0.19406806  0.        ]
   [ 0.          0.          0.07356987  0.        ]]

  [[ 0.          0.          0.          0.07831872]
   [ 0.          0.          0.         -0.20152585]
   [ 0.          0.          0.          0.07639708]]]


 [[[-0.24746819  0.          0.          0.        ]
   [-0.41985583  0.          0.          0.        ]
   [-0.18271497  0.          0.          0.        ]]

  [[ 0.         -0.1730371   0.          0.        ]
   [ 0.         -0.29357564  0.          0.        ]
   [ 0.         -0.12775972  0.          0.        ]]

  [[ 0.          0.  

In [45]:
e1, e2, e3, e4 = tf.eye(4).numpy()
e1

array([1., 0., 0., 0.], dtype=float32)

In [54]:
out = None
z1 = tf.matmul(tf.transpose(layer.kernel),tf.transpose(x)).numpy()
for k, ek in enumerate([e1,e2,e3,e4]):
    for j, ej in enumerate([e1,e2,e3,e4]):
        tmp = tf.tensordot(ej, ek, axes=0)
        u = x[0][k]*tf.nn.sigmoid(z1[j][0])*(1-tf.nn.sigmoid(z1[j][0]))*ej 
        if out is None:    
            out = tf.tensordot(u , tmp, axes=0)
        else:
            out += tf.tensordot(u , tmp, axes=0)
out            

<tf.Tensor: shape=(4, 4, 4), dtype=float32, numpy=
array([[[ 0.02505624,  0.03619251, -0.17879818,  0.12234793],
        [ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ]],

       [[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.02497404,  0.03607376, -0.17821154,  0.12194651],
        [ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ]],

       [[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.02311045,  0.0333819 , -0.16491322,  0.11284673],
        [ 0.        ,  0.        ,  0.        ,  0.        ]],

       [[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.0

In [55]:
z1 = tf.matmul(tf.transpose(layer.kernel),tf.transpose(x)).numpy()
z1

array([[ 0.22781518,  0.22349454],
       [-0.2551657 , -0.6303885 ],
       [ 0.6172855 ,  0.21629965],
       [ 0.21724278,  0.43189365]], dtype=float32)

In [56]:
z1 = tf.matmul(x, layer.kernel).numpy()
z1

array([[ 0.22781515, -0.25516564,  0.6172855 ,  0.21724276],
       [ 0.22349453, -0.6303885 ,  0.21629965,  0.43189365]],
      dtype=float32)

In [52]:
#batch dim
b1, b2 = tf.eye(2).numpy()
#create the unit tensors ek abd ej
e1, e2, e3 = tf.eye(3).numpy()
f1, f2, f3, f4 = tf.eye(4).numpy()

In [53]:
out = None
y = tf.matmul(x, layer.kernel).numpy()
for b, eb in enumerate([b1,b2]):
    for k, ek in enumerate([f1,f2,f3,f4]):
        for j, ej in enumerate([e1,e2,e3]):
            tmp = tf.tensordot(ej, ek, axes=0)
            u = x[b][j]*tf.nn.sigmoid(y[b][k])*(1-tf.nn.sigmoid(y[b][k]))*ek 
            v = tf.tensordot( eb,u, axes=0)
            if out is None:    
                out = tf.tensordot(v , tmp, axes=0)
            else:
                out += tf.tensordot(v , tmp, axes=0)
out            

<tf.Tensor: shape=(2, 4, 3, 4), dtype=float32, numpy=
array([[[[-0.32016885,  0.        ,  0.        ,  0.        ],
         [-0.08274183,  0.        ,  0.        ,  0.        ],
         [ 0.24561524,  0.        ,  0.        ,  0.        ]],

        [[ 0.        , -0.24315913,  0.        ,  0.        ],
         [ 0.        , -0.06284007,  0.        ,  0.        ],
         [ 0.        ,  0.18653779,  0.        ,  0.        ]],

        [[ 0.        ,  0.        , -0.32649165,  0.        ],
         [ 0.        ,  0.        , -0.08437586,  0.        ],
         [ 0.        ,  0.        ,  0.25046575,  0.        ]],

        [[ 0.        ,  0.        ,  0.        , -0.27656832],
         [ 0.        ,  0.        ,  0.        , -0.07147407],
         [ 0.        ,  0.        ,  0.        ,  0.21216741]]],


       [[[ 0.02925581,  0.        ,  0.        ,  0.        ],
         [ 0.0272547 ,  0.        ,  0.        ,  0.        ],
         [ 0.15074648,  0.        ,  0.        ,  0.  

In [5]:
#batch dim
b1, b2 = tf.eye(2).numpy()
#create the unit tensors ek abd ej
e1, e2, e3 = tf.eye(3).numpy()
f1, f2, f3, f4 = tf.eye(4).numpy()

#Compute Derivative 
jacobian = None
y = tf.matmul(x, layer.kernel).numpy()
for b, eb in enumerate([b1,b2]):
    for k, ek in enumerate([f1,f2,f3,f4]):
        for j, ej in enumerate([e1,e2,e3]):
            tmp = tf.tensordot(ej, ek, axes=0)
            u = x[b][j]*tf.nn.sigmoid(y[b][k])*(1-tf.nn.sigmoid(y[b][k]))*ek 
            v = tf.tensordot( eb,u, axes=0)
            if jacobian is None:    
                jacobian = tf.tensordot(v , tmp, axes=0)
            else:
                jacobian += tf.tensordot(v , tmp, axes=0)
print(jacobian)            

tf.Tensor(
[[[[ 0.07960079  0.          0.          0.        ]
   [-0.2048248   0.          0.          0.        ]
   [ 0.07764769  0.          0.          0.        ]]

  [[ 0.          0.07504999  0.          0.        ]
   [ 0.         -0.1931149   0.          0.        ]
   [ 0.          0.07320855  0.          0.        ]]

  [[ 0.          0.          0.0754204   0.        ]
   [ 0.          0.         -0.19406804  0.        ]
   [ 0.          0.          0.07356987  0.        ]]

  [[ 0.          0.          0.          0.07831872]
   [ 0.          0.          0.         -0.20152584]
   [ 0.          0.          0.          0.07639708]]]


 [[[-0.24746819  0.          0.          0.        ]
   [-0.41985583  0.          0.          0.        ]
   [-0.18271497  0.          0.          0.        ]]

  [[ 0.         -0.17303711  0.          0.        ]
   [ 0.         -0.29357567  0.          0.        ]
   [ 0.         -0.12775972  0.          0.        ]]

  [[ 0.          0.  

In [61]:
z1 = tf.matmul(x, layer.kernel).numpy()
sigmoid_partials = tf.sigmoid(z1)*(1-tf.sigmoid(z1))
sigmoid_partials

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.24678412, 0.2459744 , 0.22761956, 0.2470734 ],
       [0.24690394, 0.22672008, 0.24709855, 0.23869483]], dtype=float32)>

In [103]:
out = None
for b, eb in enumerate([b1,b2]):
    for k, ek in enumerate([e1,e2,e3,e4]):
        for j, ej in enumerate([e1,e2,e3,e4]):
            tmp = tf.einsum('bj,j,k->bjk',x, ej, ek)
            #u = x[b][j]*tf.nn.sigmoid(z1[b][k])*(1-tf.nn.sigmoid(z1[b][k]))*ek 
            u = tf.einsum('bk,b,k->bk',sigmoid_partials, eb,ek)
            #v = tf.tensordot( eb,u, axes=0)
            if out is None:    
                out = tf.einsum('bjk,bl->bkl',u , tmp, axes=0)
            else:
                out += tf.einsum('bjk,bl->bkl',u , tmp, axes=0)
            
            
out

TypeError: Invalid keyword arguments for einsum: axes

In [41]:
z1[1][0], x[0][0]

(-0.42387748, <tf.Tensor: shape=(), dtype=float32, numpy=0.22791123>)

In [12]:
inp_vector = tf.keras.layers.Input(shape=(3,), name='input')
x = tf.keras.layers.Dense(units=4, activation='tanh',
                          name='hidden', use_bias=False)(inp_vector)
x = tf.keras.layers.Dense(units=1, activation='linear',
                          name='output', use_bias=False)(x)
model = tf.keras.Model(inputs =[inp_vector], outputs=x)
print(model.summary())

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (InputLayer)           [(None, 3)]               0         
_________________________________________________________________
hidden (Dense)               (None, 4)                 12        
_________________________________________________________________
output (Dense)               (None, 1)                 4         
Total params: 16
Trainable params: 16
Non-trainable params: 0
_________________________________________________________________
None


In [108]:
X = tf.random.uniform([2, 3])
Y = tf.random.uniform([2, 1])

In [109]:
def mse(y_true, y_pred):
    return 1/2*tf.reduce_mean(tf.square(y_true-y_pred))

In [110]:
y_pred = model(X)
y_pred

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 0.3195117 ],
       [-0.60540116]], dtype=float32)>

In [111]:
loss = sse(Y, y_pred)
loss

<tf.Tensor: shape=(), dtype=float32, numpy=0.6320775>

In [112]:
with tf.GradientTape(persistent=True) as tape:
    y_pred = model(X)
    loss = mse(Y, y_pred)
gradient = tape.gradient(loss, model.trainable_variables)
print(gradient)

[<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.53669715, -0.07310512,  0.33200443,  0.1712477 ],
       [-0.27924216, -0.05345759,  0.18802422,  0.11037983],
       [-0.5738147 , -0.10320733,  0.37978774,  0.2176531 ]],
      dtype=float32)>, <tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 0.16283968],
       [-0.63626456],
       [-0.32919315],
       [-0.51200455]], dtype=float32)>]


In [113]:
with tf.GradientTape(persistent=True) as tape:
    y_pred = model(X)
    loss = sse(Y, y_pred)
j = tape.jacobian(loss, model.get_layer('output').kernel)

print(j)

tf.Tensor(
[[ 0.16283968]
 [-0.63626456]
 [-0.32919315]
 [-0.51200455]], shape=(4, 1), dtype=float32)


In [114]:
#d2
with tf.GradientTape(persistent=True) as tape:
    y_pred = model(X)
    loss = sse(Y, y_pred)
j = tape.jacobian(loss, y_pred)

print(j)

tf.Tensor(
[[-0.22074994]
 [-0.76377153]], shape=(2, 1), dtype=float32)


In [115]:
#d1
with tf.GradientTape(persistent=True) as tape:
    hidden_out = model.get_layer('hidden')(X)    
    y_pred = model.get_layer('output')(hidden_out)
    loss = sse(Y, y_pred)    
j = tape.jacobian(loss, hidden_out)

print(j)

tf.Tensor(
[[-0.1988977  -0.05304109  0.12701353  0.08994047]
 [-0.68816507 -0.18351659  0.43945342  0.31118453]], shape=(2, 4), dtype=float32)


In [116]:
with tf.GradientTape(persistent=True) as tape:
    hidden_out = model.get_layer('hidden')(X)    
j = tape.jacobian(hidden_out, model.get_layer('hidden').kernel)

print(j)

tf.Tensor(
[[[[0.02107724 0.         0.         0.        ]
   [0.46635082 0.         0.         0.        ]
   [0.76214755 0.         0.         0.        ]]

  [[0.         0.02411753 0.         0.        ]
   [0.         0.5336198  0.         0.        ]
   [0.         0.8720839  0.         0.        ]]

  [[0.         0.         0.02594353 0.        ]
   [0.         0.         0.5740215  0.        ]
   [0.         0.         0.93811154 0.        ]]

  [[0.         0.         0.         0.02573795]
   [0.         0.         0.         0.56947285]
   [0.         0.         0.         0.93067783]]]


 [[[0.77380407 0.         0.         0.        ]
   [0.27099028 0.         0.         0.        ]
   [0.61355233 0.         0.         0.        ]]

  [[0.         0.39138642 0.         0.        ]
   [0.         0.1370656  0.         0.        ]
   [0.         0.31033185 0.         0.        ]]

  [[0.         0.         0.7479956  0.        ]
   [0.         0.         0.26195204 0.     

In [117]:
 tf.einsum('ijkl->ikl',j)

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0.02107724, 0.02411753, 0.02594353, 0.02573795],
        [0.46635082, 0.5336198 , 0.5740215 , 0.56947285],
        [0.76214755, 0.8720839 , 0.93811154, 0.93067783]],

       [[0.77380407, 0.39138642, 0.7479956 , 0.5428702 ],
        [0.27099028, 0.1370656 , 0.26195204, 0.19011605],
        [0.61355233, 0.31033185, 0.5930887 , 0.43044397]]], dtype=float32)>

In [118]:
d2 =  -1/2*(Y - y_pred)
dE_dW2 = d2*hidden_out
dE_dW2 , d2, hidden_out

(<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[-0.10066434, -0.06757095, -0.03495735, -0.03998099],
        [ 0.26350403, -0.5686936 , -0.2942358 , -0.47202358]],
       dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[-0.22074994],
        [-0.76377153]], dtype=float32)>, <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[ 0.4560107 ,  0.30609727,  0.15835722,  0.18111436],
        [-0.34500372,  0.744586  ,  0.38524058,  0.6180167 ]],
       dtype=float32)>)

In [119]:
d1 = tf.tensordot( d2,model.get_layer('output').kernel, axes = [[1],[1]])
d1


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.1988977 , -0.05304109,  0.12701353,  0.08994047],
       [-0.68816507, -0.18351659,  0.43945342,  0.31118453]],
      dtype=float32)>

In [120]:
d1.shape, j.shape

(TensorShape([2, 4]), TensorShape([2, 4, 3, 4]))

In [121]:
tf.tensordot(d1, j, axes=[[0,1],[0,1]])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.53669715, -0.07310512,  0.33200443,  0.17124769],
       [-0.27924216, -0.05345759,  0.18802422,  0.11037983],
       [-0.5738147 , -0.10320733,  0.3797877 ,  0.2176531 ]],
      dtype=float32)>

# Final BP

In [ ]:
y_pred = model(X)
loss = mse(Y, y_pred)


In [122]:
batch_size=5
X = tf.random.uniform([batch_size, 3])
Y = tf.random.uniform([batch_size, 1])
def mse(y_true, y_pred):
    return 1/2*tf.reduce_mean(tf.square(y_true-y_pred))
with tf.GradientTape(persistent=True) as tape:
    y_pred = model(X)
    loss = mse(Y, y_pred)
gradient = tape.gradient(loss, model.trainable_variables)
print(gradient)

[<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.49144644, -0.14467056,  0.42745242,  0.19965783],
       [-0.49153632, -0.1501189 ,  0.3929908 ,  0.20273186],
       [-0.45179912, -0.11114688,  0.31837663,  0.17446922]],
      dtype=float32)>, <tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 0.5309386 ],
       [-0.56461114],
       [-0.44166878],
       [-0.746581  ]], dtype=float32)>]


In [124]:
d2 =  -1/batch_size*(Y - y_pred)
d1 = tf.tensordot( d2, model.get_layer('output').kernel,
                  axes = [[1],[1]])

In [155]:
d2 = -1/batch_size*(Y - y_pred)
d1 = tf.einsum('bi,jk->bj',d2, 
         model.get_layer('output').kernel)

In [130]:
d1, d2

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[-0.19179365, -0.05114662,  0.12247697,  0.08672805],
        [-0.20877399, -0.05567485,  0.13332039,  0.09440646],
        [-0.25256675, -0.0673533 ,  0.16128589,  0.11420932],
        [-0.32894233, -0.08772077,  0.21005836,  0.14874594],
        [-0.12349191, -0.03293223,  0.07886035,  0.05584237]],
       dtype=float32)>, <tf.Tensor: shape=(5, 1), dtype=float32, numpy=
 array([[-0.2128654 ],
        [-0.2317113 ],
        [-0.28031543],
        [-0.36508214],
        [-0.13705955]], dtype=float32)>)

In [134]:
d2

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[-0.2128654 ],
       [-0.2317113 ],
       [-0.28031543],
       [-0.36508214],
       [-0.13705955]], dtype=float32)>

In [138]:
#d2
with tf.GradientTape(persistent=True) as tape:
    y_pred = model(X)
    loss = sse(Y, y_pred)
j = tape.jacobian(loss, y_pred)

print(j)

tf.Tensor(
[[-0.2128654 ]
 [-0.2317113 ]
 [-0.28031543]
 [-0.36508214]
 [-0.13705955]], shape=(5, 1), dtype=float32)


In [150]:
#Computing dL1_dW1
with tf.GradientTape(persistent=True) as tape:
    hidden_out = model.get_layer('hidden')(X)    
dL1_dW1 = tape.jacobian(hidden_out, model.get_layer('hidden').kernel)
dE_dW2 = tf.einsum('bk,bi->ik', d2, hidden_out)
dE_dW1 = tf.einsum('bk,bkik->ik', d1, dL1_dW1)
print(dE_dW1, dE_dW2)

tf.Tensor(
[[-0.49144638 -0.14467056  0.42745242  0.19965784]
 [-0.49153632 -0.1501189   0.3929908   0.20273188]
 [-0.45179912 -0.1111469   0.31837663  0.17446922]], shape=(3, 4), dtype=float32) tf.Tensor(
[[ 0.5309386 ]
 [-0.56461114]
 [-0.44166878]
 [-0.746581  ]], shape=(4, 1), dtype=float32)


In [137]:
d2.shape, hidden_out.shape

(TensorShape([5, 1]), TensorShape([5, 4]))

In [128]:
dE_dW1

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.49144638, -0.14467056,  0.42745242,  0.19965784],
       [-0.49153632, -0.1501189 ,  0.3929908 ,  0.20273188],
       [-0.45179912, -0.1111469 ,  0.31837663,  0.17446922]],
      dtype=float32)>

In [147]:
tf.einsum('bk,bi->ik', d2, hidden_out)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 0.5309386 ],
       [-0.56461114],
       [-0.44166878],
       [-0.746581  ]], dtype=float32)>

In [148]:
d1.shape, dL1_dW1.shape

(TensorShape([5, 4]), TensorShape([5, 4, 3, 4]))

In [149]:
tf.einsum('bk,bkik->ik', d1, dL1_dW1)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.49144638, -0.14467056,  0.42745242,  0.19965784],
       [-0.49153632, -0.1501189 ,  0.3929908 ,  0.20273188],
       [-0.45179912, -0.1111469 ,  0.31837663,  0.17446922]],
      dtype=float32)>